name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build
        run: go build -ldflags "-X main.Version=${GITHUB_REF#refs/tags/}" -o rockfmScraper
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: rockfmScraper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
